apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zhza
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zhza
    app.kubernetes.io/part-of: tkwch-fix-0075-0051-app
  name: devfile-sample-zhza
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zhza
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zhza
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0051-tenant/tkwch-fix-0075-0051-app/devfile-sample-zhza@sha256:b0738d6dc3b0f7d76a203086261e3f54dd26b847952d4e607e387c0d0014cf54
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
